### ISSUE TITLE
Could not initialize state backend

### ISSUE THREAD

**Issue by metalgold** [mesoshq/flink-framework#1]
Hi,

I have deployed the flink-framework using Marathon (using the config provided in the readme) and tried to start a sample app in flink, but then I got:

```java
java.lang.RuntimeException: Could not initialize state backend. 
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setup(AbstractStreamOperator.java:121)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.setup(AbstractUdfStreamOperator.java:82)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:276)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createChainedOperator(OperatorChain.java:271)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.createOutputCollector(OperatorChain.java:212)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:105)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:225)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:584)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.flink.configuration.IllegalConfigurationException: Cannot create the file system state backend: The configuration does not specify the checkpoint directory 'state.backend.fs.checkpointdir'
	at org.apache.flink.runtime.state.filesystem.FsStateBackendFactory.createFromConfig(FsStateBackendFactory.java:47)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.createStateBackend(StreamTask.java:695)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.setup(AbstractStreamOperator.java:119)
	... 9 more
```

My question is: how can I configure the state backend using the Marathon config json/docker image?

**Comment by tobilg** [comment]
Have a look at the https://github.com/mesoshq/flink#configuration-properties section of the underlying Docker image.

You should be able to pass the configuration as env variable like this:

```javascript
...
"env": {
    "ZK_URL": "172.17.10.101:2181,172.17.10.102:2181,172.17.10.103:2181",
    "LOG_LEVEL": "debug",
    "state_backend_fs_checkpointdir": "/a/path/to/an/existing/folder/of/the/Docker/image"
}
...
```

I haven't explicitly tested this though. Also, be aware that the checkpointing data will only be persisted in the container, and not on the hosts.

I wouldn't really recommend to run production applications (yet) with this framework. Also, there will be an official Mesos support coming with version 1.2, which will probably released soon:

https://issues.apache.org/jira/browse/FLINK-1984

You could also check http://stackoverflow.com/questions/36645274/why-standalone-ha-flink-cluster-doesnt-save-checkpoints-to-state-backend-fs-ch for further info.

Possibly using `env.setStateBackend(new MemoryStateBackend());` is not what you would want, but it would avoid having to use an actual file system.

**Comment by metalgold** [comment]
Thank you for the pointer (pun intended) to the dockerfile configuration.
I am trying it out right now and will get back with my results.
Currently I am just evaluating the mesos stack so I don't need a production-like environment right now.

**Comment by tobilg** [comment]
Can this be closed @lastcosmonaut?

**Comment by metalgold** [comment]
Sorry.
Here's what I tried:
I could run the two docker images using marathon from this link using the parameters: https://github.com/mesoshq/flink#configuration-properties

It seemed to me, that the mesos-framework Code hard codes the parameters which it will pass to the task and job managers. 

I'm fine with the other option for now. Thank you again for your help!

**Comment by tobilg** [comment]
So, to summarized, you got it to work? Thanks!
